### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by zrzka**
* Switch edition to 2018 (`rustc >= 1.31`)
* Split `main.rs` into couple of other modules & refactor to smaller functions
  * Especially separate `mount` & `unmount` functions, because the previous flow with the comment _Carry on with mounting - unmounting is completely handled above_ was weird
* Use `log` & `env_logger` for logging
* Use `clap` for arguments parsing

There's not (shouldn't be) even a slight change in the behavior.

### CODE REVIEW

**Comment by zrzka** [comment]
Binary file size was increased from `2_477_568` to `4_434_640` bytes with all these new crates. Don't know if it's an issue. Can be optimized if necessary (like custom `info!`, ... macros instead of `log`, ...).

**Comment by zrzka** [comment]
Pushed some optimizations for `profile.release`:

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'

The size is down to `2_368_616`, which is even smaller then it was.

**Comment by zrzka** [comment]
Also, I don't know which compiler version is used across balenaOS, but I'd recommend `1.33`, because `jemalloc` was removed and system allocator is used (even smaller binary).

**Comment by agherzan** [comment]
@zrzka Shall we close this? It looks like an old piece of work.

**Pull request closed without merging**
